# Generated by Django 3.1 on 2020-08-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_qna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QnA',
            new_name='Question',
        ),
    ]
