# Generated by Django 3.1 on 2020-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200814_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, default=3, upload_to='blog/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
