# Generated by Django 3.1 on 2020-08-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_questioncomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionComment',
            new_name='Answer',
        ),
    ]
