# Generated by Django 3.1 on 2020-08-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
